### ISSUE TITLE
Instructions for testing don't work

### ISSUE THREAD

**Issue by andyfaff** [DiamondLightSource/islatu#3]
I'm following the instructions in README.md to install islatu and run the tests. I start off with a clean conda environment, with no other packages installed:

```
python setup.py build
python setup.py install
pytest
```

The first issue is that pytest isn't installed in a clean environment, the instructions don't say to install pytest. 
If I install pytest I get the following error:

```
ImportError while loading conftest '/Users/anz/Downloads/islatu/tests/conftest.py'.
tests/conftest.py:17: in <module>
    from islatu.io import I07Nexus, i07_nxs_parser, i07_dat_to_dict_dataframe
../../miniconda3/envs/dev3/lib/python3.9/site-packages/islatu/io.py:16: in <module>
    import nexusformat.nexus.tree as nx
E   ModuleNotFoundError: No module named 'nexusformat'
```

Then I get:
```
ImportError while importing test module '/Users/anz/Downloads/islatu/tests/unit/test_data.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../miniconda3/envs/islatu/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/test_data.py:6: in <module>
    from pytest_lazyfixture import lazy_fixture as lazy
E   ModuleNotFoundError: No module named 'pytest_lazyfixture'
```

There's also a whole load more packages that seem to be needed to run the tests. Most of them seem to be in the requirements.txt file, so perhaps the instructions should be amended to say:

```
install via:
python -m pip install . -r requirements.txt

test via:
pytest
```

or something like that.

**Comment by daguiam** [comment]
I have followed the installation instructions in the [documentation](https://islatu.readthedocs.io/en/latest/installation.html), using `pip install islatu` and I get the same missing packages error.

**Comment by RBrearton** [comment]
My apologies for the outdated README; I have a bad habit of neglecting these things in favour of development. I had indeed been installing with `pip install . -r requirements.txt`; I've explicitly included this in the README now. The pip downloadable islatu now also ships with the tools required for testing, so if the repo has been cloned then a simple `pip install islatu` followed by `pytest` should also run the tests. I'll mark this as closed since I've tested it on a couple of computers, but do let me know if you encounter any further issues.
